[package]
name = "kbd-parser"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
pest = "2.1.1"
pest_derive = "2.1.0"
pest-ast = "0.3.3"
from-pest = "0.3.1"
derivative = "1.0.2"
